### ISSUE TITLE
Upgrade sqlx dependency to 0.8.0 and fix build issue with undefined feature sqlx:rust_decimal

### ISSUE THREAD

**Issue by arshadm** [jeremychone/rust-sqlb#15]
I am working on a production app which is using sqlb, we use both postgres and sqlite. Unfortunately, upgrading to sqlx 0.8.0 caused a dependency issue with sqlb as it is on 0.7.x and the sqlite dependencies are incompatible.

I have update the sqlx dependency, and also fixed a compilation issue due to a missing feature which the latest version of cargo picked up. 

I also modified the tests to pickup the database URL from the environment variable DATABASE_URL (the existing value is used as fallback). This is the same variable that the sqlx macros use.

**Comment by jeremychone** [comment]
@arshadm I was planning to merge this PR. Any reason why you closed it?
I would probably do a version bump.

Btw, at this point, I am using sea-query as the SQL builder and modql (a crate I created) for extra helpers.
See code: https://github.com/rust10x/rust-web-app
See migration video: https://www.youtube.com/watch?v=-dMH9UiwKqg

But I am happy to do the merge and do a point version.

Eventually, I am probably planning to come back to this library and make it more "SQL connector" independent and more "string" based than sea-query, but I haven't fully decided yet.

**Comment by arshadm** [comment]
@jeremychone I closed the issue, but the PR is open. If you need the issue open, then by all mean re-open it. I had a look at sea-query, but it was too sophisticated for my needs, I really needed an easy to build query string for sqlx and the main use is the field names.

**Comment by jeremychone** [comment]
@arshadm Ha, you are correct. I got confused. All good!
