### ISSUE TITLE
README could mention to not enable conflicting sqlx runtime feature

### ISSUE THREAD

**Issue by eboody** [jeremychone/rust-sqlb#2]
I noticed that the sqlb crate has the following features enabled for sqlx:

```toml
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "time", "uuid"] }
```

According to my understanding, `sqlx` does not support having conflicting runtime features specified. Specifically, the `runtime-tokio-rustls` feature conflicts with other runtime features.

I believe it would be beneficial to mention this in the `sqlb` crate's README file to avoid potential issues. It could be something like:

```
Note: sqlb has "runtime-tokio-rustls" enabled by the sqlx crate. Do not enable a conflicting runtime feature when adding sqlx to your project.
```

Would it be appropriate to open a PR adding this note to the README or documentation to help users have a smoother experience when using sqlb with sqlx?

**Comment by jeremychone** [comment]
Hi, @eboody, this was a good ticket to have. Did you do the PR or do you want me to update the readme.

**Comment by eboody** [comment]
sounds good! I created a pull request #3

**Comment by jeremychone** [comment]
@eboody PR was merged and conflict resolved. All good. Thanks!
