### ISSUE TITLE
Bug: sqlb::Bindable! or sqlb::Fields doesn't seem to be working with custom enums

### ISSUE THREAD

**Issue by justinleahy** [jeremychone/rust-sqlb#6]
Hello Jeremy, I've been following along with your Rust Web App TodoMVC tutorials for implementing my own application. It's been a fantastic help with what I'm trying to accomplish. However, when working with sqlb I seem to be running into an issue with the bindable! macro. I've looked over your source code for the YouTube series as well as the sqlb source and I can't seem to figure out why this is returning an error. Any help is greatly appreciated and if you need more of my source code please let me know.

Thank you,

Justin Leahy

**Error:**

```
error[E0277]: the trait bound `Option<TransactionTypes>: SqlxBindable` is not satisfied
  --> src/model/portfolio.rs:49:10
   |
49 | #[derive(sqlb::Fields, Clone)]
   |          ^^^^^^^^^^^^ the trait `SqlxBindable` is not implemented for `Option<TransactionTypes>`
   |
   = help: the following other types implement trait `SqlxBindable`:
             Option<&std::string::String>
             Option<&str>
             Option<OffsetDateTime>
             Option<Uuid>
             Option<bool>
             Option<f32>
             Option<f64>
             Option<i16>
           and 4 others
   = note: required for `Field<'_>` to implement `From<(&str, Option<TransactionTypes>)>`
   = note: required for `(&str, Option<TransactionTypes>)` to implement `Into<Field<'_>>`
   = note: this error originates in the derive macro `sqlb::Fields` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
```

**Code:**

```rust
#[derive(sqlb::Fields, Clone)]
pub struct TransactionPatch {
    pub account_id: Option<i32>,
    pub stock_id: Option<i32>,
    pub date: Option<String>,
    pub shares_whole: Option<i64>,
    pub shares_decimal: Option<i64>,
    pub shares_decimal_exponent: Option<i64>,
    pub price_dollars: Option<i64>,
    pub price_cents: Option<i64>,
    pub transaction_type: Option<TransactionTypes>
}

#[derive(sqlx::Type, Debug, Clone, PartialEq, Eq)]
#[sqlx(type_name = "transactiontypes")]
#[sqlx(rename_all = "lowercase")]
pub enum TransactionTypes {
    Buy,
    Sell,
    DRIP,
}
sqlb::bindable!(TransactionTypes);
```

**Comment by justinleahy** [comment]
Adding more information since debugging this I've found that removing Option type from transaction_type resolves the error but this doesn't seem like the correct way to resolve this problem. Theoretically there never should be a null transaction_type but in case there is using the Option type would be a good practice to keep.
```rust
#[derive(sqlb::Fields, Clone)]
pub struct TransactionPatch {
    pub account_id: Option<i32>,
    pub stock_id: Option<i32>,
    pub date: Option<String>,
    pub shares_whole: Option<i64>,
    pub shares_decimal: Option<i64>,
    pub shares_decimal_exponent: Option<i64>,
    pub price_dollars: Option<i64>,
    pub price_cents: Option<i64>,
    pub transaction_type: TransactionTypes
}
```

**Comment by jeremychone** [comment]
@justinleahy Sorry for the delay. 

So, the issue, is that if it is `TransactionTypes` it works, but `Option<TransactionTypes>` it does not, right? 

If that is the case, it makes sense, and I need to look into it.

**Comment by KaiserBh** [comment]
> @justinleahy Sorry for the delay.
> 
> So, the issue, is that if it is `TransactionTypes` it works, but `Option<TransactionTypes>` it does not, right?
> 
> If that is the case, it makes sense, and I need to look into it.

Yes that seem to be the case, also running into the same problem. Having Option<T> leads to error. I think generic implementation for Option<T> where T is the type that the trait has been implemented for is missing.

**Comment by jeremychone** [comment]
@KaiserBh This is a good enhancement/fix I can do. Can you separate ticket for that. 

> In short in the code, I `"` surround the table names to be safe and do not handle the case where there is a `.`. Should be trivial to fix.

**Comment by jeremychone** [comment]
@justinleahy I remember the issue now. I had trouble doing the `SqlxBindable` blanket implementation for `Option<T>`. Let me give it another try. Hopefully, I was missing something obvious.

**Comment by jeremychone** [comment]
This was just fixed as part of the `0.3.6` released. Thank you for reporting. 

Note: This required the `SqlxBindable` signature to have a very minor change (lifetime needed to be added on &self), but this should be pretty transparent.

**Comment by jeremychone** [comment]
@KaiserBh I just entered #8 to add support for schema name in table names. Will be part of `v0.3.7`

**Comment by KaiserBh** [comment]
Thank you so much @jeremychone, I really appreciate it. I was just gonna do raw sql for them but if I can just use sql builder to create the generic stuff like CRUD it will be better.
